### ISSUE TITLE
Checklist Sequelize

### ISSUE THREAD

**Issue by iamlucasgomes** [iamlucasgomes/trybe-exercises#87]
## Banco de dados rodando
* [ ]  Instancia MySQL rodando.

Como subir uma instancia MySQL com Docker Compose
## Instalação das dependências
OBS: Na raiz da pasta do projeto

* [ ]  npm init -y
* [ ]  npm  install express express-async-errors  sequelize mysql2 dotenv
* [ ]  npm -D  install nodemon sequelize-cli
* [ ]   Criar uma pasta src
* [ ]   Criar o arquivo .sequelizerc na raiz do projeto com o seguinte código:

Código do .sequelizerc
* [ ]  Acesse a pasta src e rode o seguinte comando: npx sequelize-cli init
* [ ]  Verifique se as pastas config, models, migrations e seeders foram criadas
* [ ]  sair da pasta src
* [ ]  Alterar a extensão do arquivo config.json para config.js e colocar o seguinte trecho de código

Código do config,js
* [ ]   Altere a linha 9 do arquivo /models/index.js

```
const config = require(__dirname + '/../config/config.json')[env]; // configuração antiga
const config = require(__dirname + '/../config/config.js')[env];   // configuração nova
```

### Conexão com o banco
* [ ]  Crie o arquivo .env na raiz do projeto
* [ ]  Colocar o seguinte trecho de código no .env

Código do .env
* [ ]   rodar o comando npx sequelize db:create
* [ ]   rodar o comando npx sequelize model:generate --name course --underscored --attributes name:string,description:string,creation_date:date,active:boolean
* [ ]  Dentro da pasta model, crie um arquivo course.js e coloque o seguinte código:

Código da model course.js
* [ ]  rodar npx sequelize db:migrate
* [ ]  rodar npx sequelize seed:generate --name course
* [ ]  Popular a seed exemplo no código da aula 6.1 e remover o atributo duration dos objetos neste arquivo ou criar uma coluna duration do tipo inteiro
* [ ]  rodar npx sequelize db:seed:all
 
### Funcionalidades do Projeto
* [ ]  Agora estamos com nossa tabela courses criada e populada no banco, a model course também já foi criada
* [ ]  A partir deste momento, você deve seguir os mesmos passos que viu nas seções anteriores para a criação do service e controller para course, além da criação das rotas, middlewares e os arquivos app.js e server.js
* [ ]  Lembre também que os métodos chamados no service são nativos da biblioteca do Sequelize, como o create para inserir registros, o findAll para buscar todos registros, o update para atualizar um registro e o destroy para remover um registro
